version: '3.8'
services:
  web:
    build: web
    expose:
      - 80
    labels:
      - "traefik.http.routers.web.rule=Host(`localhost`)"
  api:
    build: api
    expose:
      - 80
    labels:
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
