version: '3.8'
services:
  web:
    build: web
    deploy:
      mode: replicated
      replicas: 2
    expose:
      - 80
    labels:
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=http"
      - "traefik.http.routers.secureweb.rule=Host(`localhost`)"
      - "traefik.http.routers.secureweb.entrypoints=https"
      - "traefik.http.routers.secureweb.tls=true"
  api:
    build: api
    deploy:
      mode: replicated
      replicas: 4
    expose:
      - 80
    labels:
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.routers.secureapi.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.secureapi.entrypoints=https"
      - "traefik.http.routers.secureapi.tls=true"
      - "traefik.http.services.api-l5-http.loadbalancer.sticky.cookie=true"
  reverse-proxy:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certificates:/etc/traefik/certificates
      - ./traefik.yml:/etc/traefik/traefik.yml
